image: mono:latest

stages:
    - test
    - deploy

before_script:
    - apt-get -qq update
    - apt-get -yqq install git
    - apt-get -yqq install wget
    - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - mono nuget.exe restore -NonInteractive

cache:
  paths:
  - .veronique/

release:
    stage: deploy
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.nupkg
    script:
        - mono Build/Packages/Veronique.1.2.0/tools/Veronique.exe
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.5 /p:OutputPath="..\..\Build\Release\net45"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.5.1 /p:OutputPath="..\..\Build\Release\net451"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.5.2 /p:OutputPath="..\..\Build\Release\net452"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.6 /p:OutputPath="..\..\Build\Release\net46"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.6.1 /p:OutputPath="..\..\Build\Release\net461"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.6.2 /p:OutputPath="..\..\Build\Release\net462"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.7 /p:OutputPath="..\..\Build\Release\net47"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.7.1 /p:OutputPath="..\..\Build\Release\net471"
        - msbuild "ScreenSaver.sln" /p:Configuration="Release" /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.7.2 /p:OutputPath="..\..\Build\Release\net472"
        - mono nuget.exe pack ScreenSaver.nuspec
        - mono nuget.exe push ScreenSaver*.nupkg $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json

debug:
    stage: test
    script:
        - msbuild "ScreenSaver.sln" /p:Configuration="Debug" /p:Platform="Any CPU"